name: "Genshin Impact Helper"

# Controls when the workflow will run
on:
  schedule:
    # scheduled at 00:30 (UTC+8) everyday
    - cron: "30 8 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install packages 
        run: npm install --production
        
      - name: Run sign
        env:
          COOKIE: ${{secrets.COOKIE}}
          MAIL_HOST: ${{secrets.MAIL_HOST}}
          MAIL_USERNAME: ${{secrets.MAIL_USERNAME}}
          MAIL_PASSWORD: ${{secrets.MAIL_PASSWORD}}
          MAIL_USERNAME_TO: ${{secrets.MAIL_USERNAME_TO}}
          SERVER_KEY: ${{secrets.SERVER_KEY}}
        run: npm start
